### ISSUE TITLE
Game registered as win, but email received says loss

### ISSUE THREAD

**Issue by raybojo** [bmino/sparcPong#10]
- Won a match
- Opponent resolved the score correctly
- App correctly reflects win
- Email received says I lost

![image](https://user-images.githubusercontent.com/40669380/42522530-5ab3d3d0-8439-11e8-8d7e-c19cad537f2e.png)

Issue seems cosmetic since it's just an email, but thought it was worth noting.

**Comment by bmino** [comment]
Good catch!

The issue stems from an improper variable assignment in `MailerService.js` where the winner is actually assigned to a variable called `loser` and vice versa.

Edit:
This is fixed by commit e7db65fe5f60dddd373fd680e235df21ac8015c0 and is scheduled to be in release 3.3.0
